### PR TITLE
added .gitignore, updated README.md, index.html and style.css files

### PR DESCRIPTION
**Pull request by asnganje**
Review project

### CODE REVIEW

**Comment by asnganje** [comment]
Great job setting up your repo 👍
Your project is following the GitHub Flow rules.

**Comment by asnganje** [comment]
However, I would suggest you make sure there are no linter errors. Here is a list of instructions (https://github.com/microverseinc/linters-config/tree/master/html-css) on how to go about it.

**Comment by asnganje** [comment]
I suggest that you could have added a navigation bar on top and images for the different Trumpets. This would make the website more appealing to the targeted users

**Comment by asnganje** [comment]
Finally, congratulations for the good work but also remember to address the web hint errors 
image

**Review by mugishasam123 — COMMENTED** [review]
Hi @asnganje , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by asnganje** [comment]
Finally, congratulations on the good work. 
image

**Comment by asnganje** [comment]
However, I suggest that you could have added a navigation bar on top for easy navigation.

**Comment by asnganje** [comment]
I would also suggest you consider adding images for each trumpet to make the website more appealing to the user

**Review by Kandy-Peter — APPROVED** [review]
Hi @asnganje,

### APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

##  Optional suggestion
 
# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
